[build]
maintainer = "emiliano.heyns@iris-advies.com"
repo = "retorquere/zotero-deb"
gpgkey = "dpkg"

[release.apt-get]
archs = [ "i386", "amd64",]

[release.global-menu]
archs = [ "amd64",]

[package.zotero]
repo = "zotero/zotero"
name = "Zotero"
download = "https://www.zotero.org/download/client/dl?channel=release&platform=linux-{arch}&version={version}"
dependencies = [ "libnss3-dev",]
version = "5.0.66"
bump = 8

[package.jurism]
repo = "Juris-M/zotero"
name = "Juris-M"
download = "https://github.com/Juris-M/assets/releases/download/client%2Frelease%2F{version}/Jurism-{version}_linux-{arch}.tar.bz2"
dependencies = [ "libnss3-dev", "default-jre", "libreoffice-java-common",]
version = "5.0.66m59"
