[maintainer]
email = "emiliano.heyns@iris-advies.com"
gpgkey = "dpkg"

[zotero]
name = "Zotero"
comment = "Open-source reference manager"
categories = "Office;Education;Literature"
dependencies = [ "libnss3-dev", ]
section = "Science"
description = "Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research"

[jurism]
name = "Juris-M"
comment = "Open-source reference manager"
categories = "Office;Education;Literature"
dependencies = [ "libnss3-dev", "default-jre", "libreoffice-java-common",]
section = "Science"
description = "Juris-M is a free, easy-to-use tool to help you collect, organize, cite, and share research"

[master.github]
repo = "retorquere/zotero-deb"
release = "apt-get"

[hosting.github]
repo = "retorquere/zotero-deb"
release = "test"
